# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the verssion of Python and other tools you might need
build
  os: ubuntu-20.04
  tools:
    python: "3.10"

# bulid documentation in the docs/ directory with Sphinx
sphinx:
  configuration: source/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  installa:
  - requirements: requirements.txt
